project_id = "zaeurkbtdypdjykfxmlz"

[functions.notify-telegram-purchase]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = false

[functions.send-tutorial-approval-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.ai-content-generator]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.send-admin-otp]
verify_jwt = false
